apiVersion: apps/v1
kind: Deployment
metadata: 
   name: backened-deployment
   labels:
      app: first-app
spec: 
   replicas: 3
   selector:
      matchLabels: 
         app: first-app
   template:
      metadata:
         labels:
            app: first-app
      spec:
         containers:
         -   name: backend
             image: maitri6/node-image:latest
             ports:
             -  containerPort: 3003
             env:
             -  name: MONGO_DB_USERNAME
                valueFrom:
                   secretKeyRef:
                      name: mongodb-secret
                      key: MONGO_USERNAME
             -  name: MONGO_INITDB_ROOT_PASSWORD
                valueFrom:
                   secretKeyRef:
                      name: mongodb-secret
                      key: MONGO_PASSWORD
                       